bug-fix: new job not showing inventory fix
marlinprotocol/interface-v2 pull request #160
Opened 2024-02-12 10:29 UTC by vishwajeetraj11

Description:
When creating an order from marketplace, after creation,  it navigates to inventory dashboard and newly created job doesn't show up. 

Fix: 
Upon creation of an order, the order details go into the oyster store. 
And upon navigation to inventory dashboard, both that data is merged with the newly created order as a resultant array of jobs.

2024-02-12 10:48 UTC, nayanmarlin requested changes

2024-02-12 10:48 UTC, nayanmarlin commented on src/lib/utils/helpers/oysterHelpers.ts
> +export const combineAndDeduplicateJobs = (jobsArray1: OysterInventoryDataModel[], jobsArray2: OysterInventoryDataModel[]) => {
@vishwajeetraj11 - Add relevant variable name instead of numbers in variable for jobsArray1 and jobsArray2

2024-02-12 10:48 UTC, nayanmarlin commented on src/lib/utils/helpers/oysterHelpers.ts
> +	const addObjectsToMap = (jobs: OysterInventoryDataModel[]) => {
@vishwajeetraj11 - Please create addObjectsToMap separately.

2024-02-12 11:04 UTC, souvikmishra commented
maybe we can also add in tests for the same in this PR only

2024-02-12 11:04 UTC, vishwajeetraj11 commented on src/lib/utils/helpers/oysterHelpers.ts
> +export const combineAndDeduplicateJobs = (jobsArray1: OysterInventoryDataModel[], jobsArray2: OysterInventoryDataModel[]) => {
resolved

2024-02-13 07:54 UTC, souvikmishra approved these changes

2024-02-13 07:54 UTC, souvikmishra commented on src/lib/utils/helpers/oysterHelper.test.ts
> +type OysterInventoryDataModel = {
maybe we can use a utility type for this?

2024-02-13 07:58 UTC, souvikmishra approved these changes

2024-02-13 07:58 UTC, nayanmarlin approved these changes

2024-02-13 07:58 UTC, vishwajeetraj11 commented on src/lib/utils/helpers/oysterHelper.test.ts
> +type OysterInventoryDataModel = {
done

2024-02-13 07:58 UTC, merged