Integration tests operator registration fix
marlinprotocol/interface-v2 pull request #179
Opened 2024-03-04 09:52 UTC by vishwajeetraj11

- [x] Press the edit button in the right side of the cp url input before entering the input.

2024-03-06 09:33 UTC, nayanmarlin requested changes

2024-03-06 09:33 UTC, nayanmarlin commented on .env.example
> +VITE_WALLET_PASSWORD=""
What is VITE_WALLET_PASSWORD here @vishwajeetraj11 ? is it wallet id?

2024-03-06 09:39 UTC, vishwajeetraj11 commented on .env.example
> +VITE_WALLET_PASSWORD=""
its wallet password. i.e. metamask wallet password that a user uses to unlock wallet.

2024-03-08 04:54 UTC, nayanmarlin approved these changes

2024-03-08 06:50 UTC, souvikmishra commented on src/lib/page-components/oyster/operator/OysterOperatorRegisterPage.svelte
> +<script lang="ts" defer>
why have we added defer here?

2024-03-08 06:50 UTC, souvikmishra commented on README.md
> +refer to test/docs.md
maybe add in a relative link to the docs

2024-03-08 06:51 UTC, vishwajeetraj11 commented on src/lib/page-components/oyster/operator/OysterOperatorRegisterPage.svelte
> +<script lang="ts" defer>
removed.

2024-03-08 06:54 UTC, vishwajeetraj11 commented on README.md
> +refer to test/docs.md
added

2024-03-08 06:54 UTC, souvikmishra approved these changes

2024-03-08 06:55 UTC, merged