PR to use browser local storage for managing newly created jobs on client side
marlinprotocol/interface-v2 pull request #183
Opened 2024-03-12 10:15 UTC by souvikmishra

2024-03-12 10:19 UTC, nayanmarlin requested changes

2024-03-12 10:19 UTC, nayanmarlin commented on src/lib/data-stores/localStorageStore.ts
> +	console.log(
is this console.log intentional? @souvikmishra

2024-03-12 10:21 UTC, souvikmishra commented on src/lib/data-stores/localStorageStore.ts
> +	console.log(
Yes

2024-03-12 10:39 UTC, nayanmarlin approved these changes

2024-03-14 11:48 UTC, vishwajeetraj11 approved these changes

2024-03-18 05:54 UTC, merged