Sidebar with Fixed bottom buttons
marlinprotocol/interface-v2 pull request #196
Opened 2024-04-02 06:42 UTC by vishwajeetraj11

2024-04-02 09:27 UTC, nayanmarlin commented
@vishwajeetraj11 - I think you need to rebase this PR with latest code in latest-ui branch.

2024-04-02 10:08 UTC, paul4702 requested changes
Can you please take a pull from the latest UI as there is a file structure change to resolve the conflicts.

2024-04-02 10:11 UTC, nayanmarlin requested changes

2024-04-02 10:11 UTC, nayanmarlin commented on src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
> +		{
@vishwajeetraj11 - Can we remove this SVG from list? as i mentioned today's call?

2024-04-02 10:11 UTC, nayanmarlin commented on src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
> +						opacity="0.4"
@vishwajeetraj11 - same here

2024-04-03 03:55 UTC, nayanmarlin approved these changes

2024-04-03 05:57 UTC, merged