Inter 47
marlinprotocol/interface-v2 pull request #202
Opened 2024-04-03 12:59 UTC by paul4702

![image](https://github.com/marlinprotocol/interface-v2/assets/162085914/26406c0d-2b62-49bd-9c21-a84752f86c8c)
![image](https://github.com/marlinprotocol/interface-v2/assets/162085914/56e96e9b-eba1-4674-bef4-fe042ace775f)
![image](https://github.com/marlinprotocol/interface-v2/assets/162085914/4c4b2678-6600-41f6-99ac-16766209d57a)

2024-04-04 03:55 UTC, nayanmarlin requested changes

2024-04-04 03:55 UTC, nayanmarlin commented on src/lib/atoms/v2/buttons/Button.dom.spec.ts
> +describe('Button', () => {
@souvikmishra - Can we Remove this duplicate spec(test) files from our v2? Ultimately, The snapshot or test cases will break in some case as we are developing new UI.

2024-04-04 03:55 UTC, nayanmarlin commented on src/lib/atoms/v2/buttons/Button.svelte
> +	$: buttonStyleClass = `${styleClass} ${buttonSize} ${buttonStyles} gap-1.5 !rounded-[100.86px]`;
@paul4702 - Can we use `cn` function here for such CSS?

2024-04-04 03:55 UTC, nayanmarlin commented on src/lib/atoms/v2/buttons/InfoButtonLink.svelte
> +	class="text-small mx-auto mt-4 h-10 w-fit gap-3 font-medium {buttonClass}"
@paul4702 - same here `cn`

2024-04-04 16:49 UTC, vishwajeetraj11 approved these changes

2024-04-04 16:49 UTC, vishwajeetraj11 commented on src/lib/atoms/v2/buttons/Button.svelte
> +	$: buttonStyleClass = `${styleClass} ${buttonSize} ${buttonStyles} gap-1.5 !rounded-[100.86px]`;
or this syntax

"{styleClass} {buttonSize} {buttonStyles} gap-1.5 !rounded-[100.86px]"

2024-04-05 04:46 UTC, nayanmarlin approved these changes

2024-04-05 04:53 UTC, merged