updated ecosystem ui
marlinprotocol/interface-v2 pull request #385
Opened 2024-06-19 13:34 UTC by paul4702

https://www.loom.com/share/c83dc2d187c74778ad266b6b04baca84?sid=b43c1f98-0fe0-4a3e-b06d-5fe01b895bfa

2024-06-19 14:54 UTC, souvikmishra requested changes

2024-06-19 14:54 UTC, souvikmishra commented on src/lib/page-components/ecosystem/EcosystemDashboard.svelte
> +		let partnerCat = !!sortedPartners.length ? sortedPartners[0]?.category[0] : '';
this line would fail if there are multiple categories for a partner, also the double negation is redundant, either we should use a `Boolean` constructor or a valid comparison

2024-06-19 14:54 UTC, souvikmishra commented on src/lib/page-components/ecosystem/EcosystemDashboard.svelte
> +	$: helpingFilter = getHelpingfilter(searchInput, sortedPartners, selectedFilter);
adding a whole new function kind of feels too much for this task, Im sure there must be an easier and more cleaner way to achieve this

2024-06-19 14:54 UTC, souvikmishra commented on src/lib/page-components/ecosystem/EcosystemDashboard.svelte
> +					partnerCat = '';
lets make the variable names explicit rather than cutting them short, would improve the maintainability of code

2024-06-19 14:54 UTC, souvikmishra commented on src/lib/page-components/ecosystem/EcosystemDashboard.svelte
> +	let helpingFilter: string;
how are you accounting for multiple filters in this string?

2024-06-20 02:38 UTC, nayanmarlin requested changes

2024-06-20 02:38 UTC, nayanmarlin commented on src/lib/page-components/ecosystem/EcosystemDashboard.svelte
> +					styleClass="font-normal {helpingFilter === filter
@paul4702 - can we use here `cn` function for conditional styling?

2024-06-20 06:23 UTC, closed without merging