basic UI setup for dark theme
marlinprotocol/interface-v2 pull request #389
Opened 2024-06-27 10:06 UTC by paul4702

2024-07-02 10:51 UTC, souvikmishra commented on src/lib/page-components/oyster/dashboard/OysterDashboardPage.svelte
> +		Hello, {shortenText($walletStore.address, 6, 6)}
is there a reason why we removed the `$connected` check?

2024-07-02 10:51 UTC, souvikmishra commented on src/lib/components/inputs/AmountInputWithMaxButton.svelte
> +				disabled={!handleUpdatedAmount || !$connected}
is there a reason why we removed `|| disabled` and `{onlyInteger}`

2024-07-02 11:08 UTC, paul4702 commented on src/lib/page-components/oyster/dashboard/OysterDashboardPage.svelte
> +		Hello, {shortenText($walletStore.address, 6, 6)}
![image](https://github.com/marlinprotocol/interface-v2/assets/162085914/34ed0906-8731-45af-82eb-9201eacb0239)


I have no idea, How this line was missed. I am updating it

2024-07-02 11:09 UTC, souvikmishra commented
also, it feels like some of the classes that we have replaced the hardcoded with are not in both light and dark configs, maybe check once

2024-07-02 11:24 UTC, paul4702 commented
> also, it seems like some of the classes that we have replaced the hardcoded colors with are not present in both light and dark configs, maybe check once @paul4702

@souvikmishra  The colors we have changed you can find them under the variable names ex: for grey-800 :  --grey-800 & you can find --grey-800 assigened to grey-800 under theme extended colors: PFA screenshot 

 I have changed the most used 6 colors 


![image](https://github.com/marlinprotocol/interface-v2/assets/162085914/bada1856-5776-4f2b-9a6b-868d81f96c18)

![image](https://github.com/marlinprotocol/interface-v2/assets/162085914/2752dd9a-420d-4050-b142-3fef35b5ad20)


![image](https://github.com/marlinprotocol/interface-v2/assets/162085914/52bf074b-19b3-4857-8080-ec5c57ef119c)

2024-07-02 11:48 UTC, vishwajeetraj11 requested changes

2024-07-02 11:48 UTC, vishwajeetraj11 commented on src/lib/components/header/sub-components/SidebarLinksGroup.svelte
> +	$: isDarkModeActive = localStorage?.getItem('theme') === 'light' ? false : true;
this check can be improved.
```$: isLightModeActive = localStorage?.getItem('theme') === 'light'```
or (use dark mode constant)
```$: isDarkModeActive = localStorage?.getItem('theme') === 'dark'```

2024-07-03 05:19 UTC, paul4702 commented on src/lib/components/header/sub-components/SidebarLinksGroup.svelte
> +	$: isDarkModeActive = localStorage?.getItem('theme') === 'light' ? false : true;
updated the condition

2024-07-03 05:32 UTC, vishwajeetraj11 approved these changes

2024-07-03 11:02 UTC, nayanmarlin requested changes

2024-07-04 05:55 UTC, paul4702 commented on src/lib/components/header/sub-components/SidebarLinksGroup.svelte
> +		<!-- Uncomment the following code to enable theme switcher -->
yes, This is a switch so, we want the code to be merged in steps and if somebody wants to test the dark theme they can uncomment it and check how it is looking as it we are pushing it to dev

2024-07-04 06:00 UTC, paul4702 commented on src/lib/page-components/dashboard/MarlinHubDashboard.svelte
> +						<img src={card.logo} alt={card.logoAlt} class="dark:bg-white" />{card.title}
Yes, It was but I am trying out a diff approach to make sure the icons look invert in color. removed it and updated the code

2024-07-04 08:21 UTC, nayanmarlin approved these changes

2024-07-05 06:04 UTC, souvikmishra approved these changes

2024-07-05 06:07 UTC, souvikmishra approved these changes

2024-07-05 06:07 UTC, merged